---
title: "Dragon element data analysis"
author: "Stephanie J. Spielman and Naman Srivastava"
output: 
  html_document:
    theme: united
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dragon)
library(ggrepel)
library(broom)

# Information about elements that may be needed eventually
dragon:::element_info %>%
  # Not present since 4.33 Ga
  filter(element != "Tc") -> elements
```

```{r model_functions}
# Define functions that will be used to parse linear models

# Return the R^2
get_model_r2 <- function(fitted_model)
{
  broom::glance(fitted_model) %>%
    pull(r.squared) %>%
    round(3)
}

get_model_formula <- function(fitted_model)
{
  broom::tidy(fitted_model) -> coefficients
  # Get coefficients into their own variables
  coefficients %>%
    filter(term == "n_elements") %>%
    pull(estimate) -> slope
  coefficients %>%
    filter(term == "(Intercept)") %>%
    pull(estimate) -> yint
  # Are we subtracting or adding the y intercept?
  if (yint >= 0)
  {
    sign <- " + "
  } else {
    sign <- " - "
  }
  
  # Get the formula as a string
  formula <- glue::glue(
              "Y = ",
              {round(slope, 3)}, "X", 
              {sign}, {abs(round(yint, 3))}
              )
  formula
}
```

```{r element_network_function}
# Function to build a network for a given element, considering only < 4.34 Ga
parse_element_network <- function(element)
{
  # Build the full oxygen network. Returns a LIST with various important stuff.
  # remember 3 colons
  dragon:::initialize_network(elements_of_interest = element, 
                              # age_range is inclusive and we don't want =4.34, so this is hopefully good enough.
                              age_range = c(4.33, 0)) -> full_oxygen
  
  # The important stuff is in `$edges` and `$locality_info` names
  oxygen_edges <- full_oxygen$edges 
  oxygen_locality <- full_oxygen$locality_info 
  
  # How many elements does element form minerals with?
  oxygen_edges %>%
    dplyr::select(to) %>%
    dplyr::distinct() %>%
    dplyr::filter(to != element) %>% # not self
    nrow() -> n_elements
  
  # How many minerals does element form?
  oxygen_edges %>%
    dplyr::select(from) %>%
    dplyr::distinct() %>%
    nrow() -> n_minerals
  
  # At how many localities? 
  oxygen_locality %>%
    # mindat_id column represents unique ID for localities
    dplyr::select(mindat_id) %>%
    dplyr::distinct() %>%
    nrow() -> n_localities
  
  # whatever is written last in the function body gets returned
  c("element" = element,
    "n_elements" = n_elements,
    "n_minerals" = n_minerals,
    "n_localities" = n_localities)
}
```


```{r build_all_networks, message=FALSE}
# Makes a tibble with four columns:
## element
## n_elements (excludes self!!)
## n_minerals
## n_localities
purrr::map_df(elements$element, parse_element_network) -> element_networks
element_networks %>%
  left_join(elements) %>%
  mutate(n_elements = as.numeric(n_elements),
         n_minerals = as.numeric(n_minerals),
         n_localities = as.numeric(n_localities)) -> element_networks_info

element_networks_info
```

## Minerals against Elements 
```{r minerals against elements plot}
# regression
#   y         ~ x          , data = dataframe x/y are in
lm(n_minerals ~ n_elements, data = element_networks_info) -> mineral_fitted_model
get_model_formula(mineral_fitted_model) -> mineral_formula
get_model_r2(mineral_fitted_model) -> mineral_r2 # this has to go somewhere??? 

# regression
#   y         ~ x          , data = dataframe x/y are in
lm(n_minerals ~ n_elements, data = element_networks_info) -> mineral_fitted_model
get_model_formula(mineral_fitted_model) -> mineral_formula
get_model_r2(mineral_fitted_model) -> mineral_r2 # this has to go somewhere??? 

ggplot(element_networks_info)+
  aes(y=n_minerals,
      x= n_elements)+
      #label = element)+
  geom_point()+
  labs(x = "Number of Elements", #Y-axis label
       y = "Number of Minerals", 
       title = "Relationship between number of elements and minerals they form", 
       subtitle = mineral_formula)+ #X-axis label
  scale_x_continuous(breaks=seq(0,80,10))+
  scale_y_log10()+
  #geom_text_repel()+
  annotate("text", x = 7.5, y = 1850, label = mineral_r2, color = "red")+
  theme_bw()
```

## Localities against Elements
```{r localities against elements plot}
# regression
#   y         ~ x          , data = dataframe x/y are in
lm(n_localities ~ n_elements, data = element_networks_info) -> localities_fitted_model
get_model_formula(localities_fitted_model) -> localities_formula
get_model_r2(localities_fitted_model) -> localities_r2 # this has to go somewhere??? 
ggplot(element_networks_info)+
  aes(y=n_localities,
      x= n_elements)+
      #label = element)+
  geom_point()+
  labs(x = "Number of Elements", #Y-axis label
       y = "Number of Localities", #X-axis label
       title = "Relationship between number of elements and the number of localities", 
       subtitle = localities_formula)+ 
  scale_x_continuous(breaks=seq(0,80,10))+
  scale_y_log10()+
  #geom_text_repel()+
  annotate("text", x = 7.5, y = 1850, label = localities_r2, color = "red")+
  theme_bw()
```
